name: Render and bundle docs

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout https://github.com/carnarez/depviz repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Node dependencies
        run: |
          npm install --global --no-audit --no-fund autoprefixer \
                                                    cssnano \
                                                    html-minifier \
                                                    postcss-cli \
                                                    terser

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir ghp-import \
                                               git+https://github.com/carnarez/astdocs@master \
                                               git+https://github.com/carnarez/markdown-extension-astdocs@master \
                                               git+https://github.com/carnarez/markdown-extension-img@master \
                                               git+https://github.com/carnarez/markdown-extension-insert@master \
                                               git+https://github.com/carnarez/markdown-extension-script@master \
                                               git+https://github.com/carnarez/markdown-render@master \
                                               jinja2 \
                                               lunr \
                                               markdown \
                                               pymdown-extensions \
                                               pyyaml

      - name: Render and bundle
        run: |
          # generate the documentation
          mkdir web/utils
          cp utils/*.py web/utils
            
          (
            cd web/utils
            ASTDOCS_WITH_LINENOS=1 astdocs . > index.md
            mv *.py ..
          )

          # render the documentation
          (
            cd web

            # will contain all rendered/bundled content
            mkdir /tmp/www

            # prepare and convert markdown files to html
            find . -name "*.md" | grep -e front-matter.md -e toc.md -v | while read f; do
              mkdir -p /tmp/www/$(dirname $f)
              cat front-matter.md $f > /tmp/md
              mv /tmp/md $f
            done
            rm front-matter.md
            render-markdown --meta="splash=nosplash" \
                            --prefix=/tmp/www \
                            --root=https://carnarez.github.io/depviz/ \
                            $(find . -name "*.md" | grep -v toc.md)
            rm toc.md

            # prepare html files
            sed -i 's|href=\"/|href=\"/depviz/|g;s|src=\"/|src=\"/depviz/|g' $(find /tmp/www -name "*.html")

            # prepare css files
            git clone --branch=bundle --depth=1 https://github.com/carnarez/markdown-render-styling.git
            cat markdown-render-styling/style.css *.css 2>/dev/null | grep -v '@import url("style-' > style.css_
            rm -fr markdown-render-styling *.css
            mv style.css_ style.css
            find . -name "*.css" | while read f; do cp $f /tmp/www/$(dirname $f); done

            # prepare js files
            find . -name "*.js" | while read f; do cp $f /tmp/www/$(dirname $f); done
          )

          # minify everything
          (
            cd /tmp/www

            # bundle css
            find . -name "*.css" | while read f; do
              postcss $f --no-map --replace --use autoprefixer
              postcss $f --no-map --replace --use cssnano
            done

            # bundle html
            find . -name "*.html" | while read f; do
              html-minifier --collapse-boolean-attributes \
                            --collapse-whitespace \
                            --minify-css true \
                            --minify-js true \
                            --output $f \
                            --remove-attribute-quotes \
                            --remove-comments \
                            --remove-empty-attributes \
                            --remove-optional-tags \
                            --remove-redundant-attributes \
                            --remove-script-type-attributes \
                            --remove-style-link-type-attributes \
                            --use-short-doctype \
                            $f
            done

            # bundle js
            find . -name "*.js" | while read f; do terser --compress --mangle --module --output $f $f; done
          )

      - name: Deploy to https://carnarez.github.io/depviz/
        run: |
          (
            cd web
            
            ghp-import --branch www --force --push /tmp/www
          )
