name: Run Python tests

on:
  push:
    branches:
      - master

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout https://github.com/carnarez/depviz repository
        uses: actions/checkout@v3

      - name: Set up Python v3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir pytest pytest-cov sqlparse

      - name: Run pytest
        run: |
          cd utils
          python -m pytest --color=yes --cov=sql_to_json --cov-report term-missing --verbose
